rwd
annakocot/CampingTemplate pull request #2
Opened 2021-02-21 13:04 UTC by annakocot

2021-02-23 20:17 UTC, furdzik requested changes

2021-02-23 20:17 UTC, furdzik commented on assets/scripts/index.js
> +scrollToTopButton.onclick = function(e) {
Nie na onclick.

https://stackoverflow.com/questions/5871640/why-is-using-onclick-in-html-a-bad-practice
https://en.wikipedia.org/wiki/Unobtrusive_JavaScript
https://medium.com/@annapeterson89/addeventlistener-vs-onclick-which-one-should-you-draft-into-your-fantasy-football-team-16ea9ae71ee0

2021-02-23 20:17 UTC, furdzik commented on assets/styles/components/_buttons.scss
> +      opacity: 1;
Po pierwsze powinny to być klasy globalne.
Pytanie czemy ukrywasz je na visibility?
Znasz różnicę miedzy visibility hidden a display block?

2021-02-23 20:17 UTC, furdzik commented on assets/styles/layout/_footer.scss
> +      margin-left: 13rem;
Dlaczego aż taki duży margines? Jest on konieczny? Możesz napisać w kilku słowach co potrzebujesz zrobić?

2021-02-23 20:17 UTC, furdzik commented on assets/styles/layout/_footer.scss
> +      width: 38rem;
Na pewno konieczne jest manipulowanie szerokością aż tak? Np max-width nie załatwił by sprawy?

2021-02-23 20:17 UTC, furdzik commented on assets/styles/layout/_footer.scss
> +    &+& {
Proszę dodaj spacje pomiedzy + a &ami

2021-02-23 20:17 UTC, furdzik commented on assets/styles/layout/_footer.scss
> +        margin-top: 0;
Te zmiany marginesów troche dziwne, nie znam Twoich motywów, ale żadko zdarzyło mi się pisać taki kod, dlatego podnoszę głos. Opiszesz mi sytuację?

2021-02-23 20:17 UTC, furdzik commented on assets/styles/layout/_nav.scss
> +.fixed-nav {
Bem nie dobry i pytanie czy fixed-nav nie powinien być jednak klasą która tylko modyfikuje element np mamy .nav i wtedy fixed-nav dodaje kolor biały i fixed. Chodzi mi o zagnieżdzenie nav w fixed nav. Tylko nie wiem jak wygląda HTML. użył color inherit dla zmiany koloru elementów. Jedynie zostaw zastosowanie hovera.

2021-02-23 20:17 UTC, furdzik commented on assets/styles/layout/_newsletter.scss
> +     @include media-breakpoint-up(landscapePhone) {
Formatowanie.

2021-02-23 20:17 UTC, furdzik commented on assets/styles/layout/_newsletter.scss
> +    margin: 0 auto;
Jak masz absoluta, to margin 0 auto nie zadziała. Po co Ci to tutaj?

2021-02-23 20:17 UTC, furdzik commented on assets/styles/layout/_newsletter.scss
> +      margin: 4rem auto;
Formatowanie.

2021-02-23 20:17 UTC, furdzik commented on assets/styles/style.scss
> +@import 'abstracts/breakpoints';
A o co chodzi z tym "abstracts"?

2021-02-23 20:17 UTC, furdzik commented on index.html
> +<script src="/assets/scripts/index.js"></script>
Coś tutaj też chyba jest coś nie tak z formatowaniem.

2021-02-24 15:52 UTC, annakocot commented on assets/styles/style.scss
> +@import 'abstracts/breakpoints';
od początku tam mam taki folder. https://itnext.io/structuring-your-sass-projects-c8d41fa55ed4 tu se wyczytałam, że tak sie robi 🤷‍♀️

2021-02-24 15:55 UTC, annakocot commented on assets/styles/layout/_newsletter.scss
> +    margin: 0 auto;
a nie wiem cos to sie tu pomieszało 😞

2021-02-24 16:45 UTC, annakocot commented on assets/styles/layout/_footer.scss
> +        margin-top: 0;
no, mam tam we wrapperze 3 ul i w desktopie są we flex-direction: row i wtedy mają margin-left, a w mobile są we flex-direction: column i wtedy mają margin-top.

2021-02-24 16:52 UTC, annakocot commented on assets/styles/layout/_footer.scss
> +      margin-left: 13rem;
tu próbuję wyśrodkować to wszystko co jest w środku footer

2021-02-24 16:53 UTC, annakocot commented on assets/styles/layout/_footer.scss
> +      margin-left: 13rem;
jakoś nie udało mi się to w żaden inny sposób...

2021-02-24 16:54 UTC, annakocot commented on assets/styles/layout/_footer.scss
> +      width: 38rem;
właśnie coś chyba popsułam i mi sie rozjeżdża inaczej... 😢

2021-02-24 16:55 UTC, annakocot commented on assets/styles/components/_buttons.scss
> +      opacity: 1;
No dzisiaj już znam, a wtedy tak zrobiłam, bo tak sie nauczyłam z kursu głupiego. Ale już więcej tak nie będę.

2021-02-24 18:12 UTC, annakocot commented on assets/scripts/index.js
> +    scrollToTopButton.className = 'button__icon--back-top hide';
znalazłam, że przedrostek js to zła praktyka

2021-02-24 18:16 UTC, annakocot commented on assets/styles/layout/_newsletter.scss
> +    margin: 0 auto;
wyrzucilam to całkiem

2021-02-24 18:17 UTC, annakocot commented on assets/scripts/index.js
> +scrollToTopButton.onclick = function(e) {
ok zmieniłam na addEventListener

2021-02-24 18:25 UTC, annakocot commented on assets/styles/layout/_nav.scss
> +.fixed-nav {
ale color inherituje mi się biały, a ja chce czarny. i nie do końca chyba rozumiem co mam zrobić z tym nav i fixed-nav 😢

2021-02-25 20:27 UTC, furdzik commented on assets/scripts/index.js
> +    scrollToTopButton.className = 'button__icon--back-top hide';
Ale rozumiem, że u- będzie ok (BEMowe utilities)?

2021-02-25 20:28 UTC, furdzik commented on assets/styles/layout/_footer.scss
> +      margin-left: 13rem;
Musiałabym zobaczyć, ale ufam że jest OK, skoro inaczej się nie udało...

2021-02-25 20:29 UTC, furdzik commented on assets/styles/layout/_footer.scss
> +      width: 38rem;
Dobra, chyba będę musiała na to spojrzeć 😃

2021-02-25 20:30 UTC, furdzik commented on assets/styles/layout/_footer.scss
> +        margin-top: 0;
To brzmi rozsądnie, chyba miałam jakiś oczoplons i inne marginesy widziałam 😄

2021-02-25 20:32 UTC, furdzik commented on assets/styles/layout/_nav.scss
> +.fixed-nav {
Nałóż  kolor na wyższy element po zmianę tła na białe. A oryginalne elementy (przed zmianą będą miały` color: inherit;`) i wtedy zadziała.

2021-02-25 20:36 UTC, furdzik commented on assets/styles/style.scss
> +@import 'abstracts/breakpoints';
Hmmm, pierwsze widzę. Na pewno z mojego punktu widzenia "utilities" jest lepszą nazwą, od razu wiadomo o co chodzi. Nigdy też się nie spotkałam z "abstracts", ale co developer to sposób. Nie każe ci tego zmienić, ale możesz jeszcze o tym poczytać. Pamiętaj, żeby zawsze weryfikować zródła, ja się staram coś traktować jako "prawdę objawioną ;)" jeśli przeczytam coś w 3 różnych zródłach 😃

2021-02-25 20:36 UTC, furdzik commented
Wrzuć jeszcze zmiany, to Ci sprawdzę 😄

2021-02-26 21:08 UTC, annakocot commented on assets/scripts/index.js
> +    scrollToTopButton.className = 'button__icon--back-top hide';
tak, tak zrobilam

2021-02-26 21:08 UTC, annakocot commented on assets/styles/layout/_footer.scss
> +      margin-left: 13rem;
nie no, moge popelniac tam jakis okropny blad...

2021-03-09 09:05 UTC, merged